### ISSUE TITLE
Undefined symbols for architecture armv7 error without CocoaPods

### ISSUE THREAD

**Issue by yuchin067** [ConnectSDK/Connect-SDK-iOS-API-Sampler#23]
According to official documents to perform a manual installation. I got the following error:

Undefined symbols for architecture armv7:
  "_OBJC_METACLASS_$_GCKCastChannel", referenced from:
      _OBJC_METACLASS_$_CastServiceChannel in libConnectSDK.a(CastServiceChannel.o)
  "_OBJC_CLASS_$_GCKCastChannel", referenced from:
      _OBJC_CLASS_$_CastServiceChannel in libConnectSDK.a(CastServiceChannel.o)
  "_OBJC_CLASS_$_DiscoveryController", referenced from:
      objc-class-ref in libConnectSDK.a(FireTVDiscoveryProvider.o)
  "_OBJC_CLASS_$_BFExecutor", referenced from:
      objc-class-ref in libConnectSDK.a(FireTVCapabilityMixin.o)
  "_OBJC_CLASS_$_GCKDeviceScanner", referenced from:
      objc-class-ref in libConnectSDK.a(CastDiscoveryProvider.o)
  "_kGCKMediaDefaultReceiverApplicationID", referenced from:
      -[CastService castWebAppId] in libConnectSDK.a(CastService.o)
  "_kGCKMetadataKeySubtitle", referenced from:

I confirm GoogleCast.framework, AmazonFling.framework and Bolts.framework have put inside Connect SDK module. The "Build Phases" with "Link Binary with Libraries" has correct setting. The "Other Linker Flags" add -ObjC.

I fully according to instructions on the manual to do, but it did have errors. Was I missing something?

This is my project. (https://drive.google.com/file/d/0B-96ynJ1excZQUVtT25USXVXVVU/view?usp=sharing)
How can I fix it, thanks.

**Comment by eunikolsky** [comment]
@yuchin067, you haven't linked the external frameworks with **the app itself**. 

https://github.com/ConnectSDK/Connect-SDK-iOS-Google-Cast/blob/master/README.md#connect-sdk-integration, step 4:
> Link GoogleCast.framework with your application target

https://github.com/ConnectSDK/Connect-SDK-iOS-FireTV/blob/master/README.asciidoc#connect-sdk-integration, step 3:
> Link AmazonFling.framework, Bolts.framework, libc++.dylib, and AdSupport.framework with your application target.

**Comment by eunikolsky** [comment]
@yuchin067, we've clarified that step in the `README`s. Please check now and thanks for reporting this.

**Comment by yuchin067** [comment]
It work around now, thank you. But it still have some problems.
It always crash, when it found the Roku TV.
The program stop in the following code:  
[apps enumerateObjectsUsingBlock:^(NSDictionary *appInfoDictionary, NSUInteger idx, BOOL *stop)
How can I fix it, thanks.

**Comment by eunikolsky** [comment]
@yuchin067, what Roku device and its firmware do you have? What ConnectSDK version do you use? Please attach a stack trace for the issue. Also, to help with the debugging, please enable logs (uncomment [line 28 in `ConnectSDK-Prefix.pch`](https://github.com/ConnectSDK/Connect-SDK-iOS-Core/blob/dev/ConnectSDK-Prefix.pch#L28)) and attach the replies from your Roku device. Thanks.

**Comment by yuchin067** [comment]
Sorry, too late for you.
The Roku firmware version is 6.2.build3467 and ConnectSDK version is 1.5.0.
The error log file as follows,
https://drive.google.com/file/d/0B-96ynJ1excZbUhvNEtWMExVTzg
Thanks.

**Comment by eunikolsky** [comment]
@yuchin067, the Roku issue is here now: https://github.com/ConnectSDK/Connect-SDK-iOS/issues/175
