### ISSUE TITLE
The webOS smart TV is not discovered.

### ISSUE THREAD

**Issue by HyconLogan** [ConnectSDK/Connect-SDK-iOS-API-Sampler#29]
It is discovered in simulator, but it is not discovered in iphone.
Do you need any other settings?

**Comment by HarshadTechmero** [comment]
Add multicast permission in info.plist, your issue will be solved

**Comment by chabelets** [comment]
> Add multicast permission in info.plist, your issue will be solved

I added com.apple.developer.networking.multicast true to my info.plist but it doesn't work
I tried to add Multicast Networking Additional Capability in apple dev console but I cant find it in my identifiers.

**Comment by HarshadTechmero** [comment]
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_multicast

You need to send request to apple for enable multicasting

**Comment by HarshadTechmero** [comment]
Hi @chabelets 

Please request apple to enable Multicasting using this link,

https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_multicast

Click [Multicast Networking Entitlement Request](https://developer.apple.com/contact/request/networking-multicast)
and give reason for enable and wait for few days, apple will allowed to enable multicasting from developer accpount

**Comment by HyconLogan** [comment]
Thanks.

**Comment by HarshadTechmero** [comment]
@HyconLogan Let me know once you done with connect and pair device.

Thanks

**Comment by chabelets** [comment]
> Hi @chabelets
> 
> Please request apple to enable Multicasting using this link,
> 
> https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_multicast
> 
> Click [Multicast Networking Entitlement Request](https://developer.apple.com/contact/request/networking-multicast) and give reason for enable and wait for few days, apple will allowed to enable multicasting from developer accpount

Thanks Harshad it works, I see my LG device but I don't have any pairing code on my TV

```
discoveryManager = DiscoveryManager.shared()
discoveryManager.pairingLevel = DeviceServicePairingLevelOn
discoveryManager.registerDefaultServices()
discoveryManager.delegate = self
```

**Comment by HarshadTechmero** [comment]
@chabelets i have same problem for pairing code. Let me know if you have any solutions for pairing code
